name: Deploy Glineze Node Typescript

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy Bot
        env:
          BOT_PATH: ${{ secrets.BOT_PATH }}
        run: |
          cd $BOT_PATH
          git reset --hard
          git pull

      - name: Build
        env:
          CONTAINER_PATH: ${{ secrets.CONTAINER_PATH }}
        run: |
          cd $CONTAINER_PATH
          docker compose build

      - name: Deploy
        env:
          BOT_PATH: ${{ secrets.BOT_PATH }}
        run: |
          sudo systemctl restart glanze-apps
